services:
  - type: web
    name: friend-django
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Friend.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.4